services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: as4-final-data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 913020
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    networks:
      - shared-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d as4-final-data && psql -U postgres -d as4-final-data -c 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 30s
    restart: always

volumes:
  postgres_db_volume:

networks:
  shared-network:
    external: true